# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
# dyanmically set providers
terraform {
  required_providers {
    oci = {
      source = "oracle/oci"
    }
    tls = {
      source = "hashicorp/tls"
    }
  }
}

# main provider for oci
provider "oci" {
  region              = "me-jeddah-1"
  auth                = "APIKey"
  config_file_profile = "DEFAULT"
}
